version: "3.9"
services:
  mongodb:
    restart: always
    image: "mongo:6.0.4-jammy"
    container_name: trade-quotes-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=abcdefgh
    ports:
      - "27017:27017"

  backend:
    build: .
    restart: always
    platform: linux/amd64
    container_name: trade-quotes-be
    environment:
      - DB_HOST=mongodb
      - SMTP_PWD=viceversa
    ports:
      - "8000:8000"
